### ISSUE TITLE
Ada file di luar folder

### ISSUE THREAD

**Issue by hadihammurabi** [Nursidiq97/naya-kursus#2]
Mas @Nursidiq97 di sini ada 2 file yang di luar folder.
Keliatannya file-file ini bisa dimasukkan ke dalam folder sesuai pertemuannya.
<img width="386" alt="image" src="https://user-images.githubusercontent.com/16364286/216800444-0de979cc-3666-43df-b970-3efff19cebc9.png">

Silakan diatur supaya lebih rapi lagi ya

**Comment by Nursidiq97** [comment]
Baik Mas...
